# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.5.0
_src_path: gh:epics-containers/ioc-template
description: A 'generic' generic IOC that provides a quick to launch IOC devcontainer.
    e.g. for developing new support modules.
git_platform: github.com
github_org: epics-containers
name: ioc-generic
repo_uri: git@github.com:epics-containers/ioc-generic.git
rtems: true
